---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pesant30/api.pesantrenku.my.id/
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R config $DEPLOYPATH
    - /bin/cp -R db $DEPLOYPATH
    - /bin/cp -R exception $DEPLOYPATH
    - /bin/cp -R middleware $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp LICENSE $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp README.md $DEPLOYPATH