@baseurl = http://localhost:3000
GET {{baseurl}}/api/pelajaran-guru HTTP/1.1

###
POST {{baseurl}}/api/pelajaran-guru HTTP/1.1
Content-Type: application/json

{
  "guruId": 1,
  "pelajaranId" : 9,
  "kelasId": 1
}

###
GET {{baseurl}}/api/pelajaran-guru/1 HTTP/1.1

###
PUT {{baseurl}}/api/pelajaran-guru/2 HTTP/1.1
Content-Type: application/json

{
  "guruId": 1,
  "pelajaranId" : 11,
  "kelasId": 1
}
###
DELETE {{baseurl}}/api/pelajaran-guru/8 HTTP/1.1