@baseurl = http://localhost:3000
GET http://localhost:3000/api/guru HTTP/1.1

###
POST http://localhost:3000/api/guru/create HTTP/1.1
Content-Type : application/json

{
  "guruName" : "Fahmi Yusuf"
}
###
GET http://localhost:3000/api/guru/2 HTTP/1.1

###
PUT http://localhost:3000/api/guru/1 HTTP/1.1
Content-Type: application/json

{
  "guruName": "Muhammad Nur Fatoni"
}
###
DELETE http://localhost:3000/api/guru/1 HTTP/1.1